### ISSUE TITLE
Importing PSAs always orients one and only one bone incorrectly?

### ISSUE THREAD

**Issue by ariannadiangelo** [DarklightGames/io_scene_psk_psa#107] opened 2024-09-16 21:41 UTC
**Versions**
Blender: 4.1.1
io_scene_psk_psa: 7.0.0

**Describe the bug**
This is very bizarre, but it happens consistently with the .PSAs I import from this game (Deceive Inc). For whatever reason, the left ear bones (always called l_ear_int across all .PSKs from the game) are always rotated in the total wrong direction. To fix it, I have to copy and paste the pose from r_ear_int flipped on the X axis. Multiple poses and multiple meshes _always_ yield this result.

**To Reproduce**
1. Import .psk and .psa from game
2. Go to Action Editor to view the .psa on the related armature
3. Go back to layout; the left ear will be visibly flipped and in the wrong position
4. To correct its position, copy and paste the pose from the right ear flipped on the X-axis

**Expected behavior**
The .PSAs import with all bones oriented in the correct direction for the pose to work.

**Screenshots**
![image](https://github.com/user-attachments/assets/5810eebd-663e-4179-8d27-cc5f3ec1f8bd) Armature with .PSA applied to it; left ear is visibly inverted
![image](https://github.com/user-attachments/assets/6ba9e1aa-4e0d-4b24-9c36-5b56a2cdd982) Corrected left ear position by copying and pasting right ear's position
![image](https://github.com/user-attachments/assets/624b1187-97a2-47f5-9aa9-c761af05f8b3) Different mesh using different .psa, same issue

**Files**
Any .psk and .psa from Deceive Inc should yield this issue.

**Additional context**
The .PSKs and .PSAs are extracted directly from the game using FModel; UModel is not used.

**Comment by cmbasnett** [comment] 2024-09-17 09:47
Please provide the PSK and PSA files so I can reproduce the issue.

**Comment by ariannadiangelo** [comment] 2024-09-17 23:50
[files.zip](https://github.com/user-attachments/files/17036479/files.zip)
Here you go. If you need more .PSKs/.PSAs, let me know, but every intro pose (.PSA) I've tried so far has done this.

**Comment by cmbasnett** [comment] 2024-09-22 06:31
@ariannadiangelo Is there maybe a .config file that should be coming along with this as well? As far as I can tell there should be no reason for the ear to be animated at all so I'm wondering if there's a .config file that may be excluding the ear.

**Comment by ariannadiangelo** [comment] 2024-09-22 22:51
Nope, here's what the path in FModel looks like: 
![image](https://github.com/user-attachments/assets/a1ecf88e-b2d3-4fc5-a089-914b43dbd0c9)
I click the AssetPathName to get to the animation, right click to get "Save as Animation", and then it is exported as a .PSA. There is no .config file.
The way intro poses work in the game is that they are either low rarity and thus "static" (small movement that loops), or high rarity that involves a ton of movement. Regardless of type, I think all the bones do technically get "animated" in the process (i.e. they have a location where they need to be, even if they don't "move").
Some of the poses HAVE imported just fine (I've only found two so far), but I cannot figure out why certain poses import with just the one ear flipped. It's unclear to me if it's limited to certain characters' skeletons only or certain types of poses.

**Comment by ariannadiangelo** [comment] 2024-09-22 23:01
For example, so far, every .psa I've imported for the character Ace has imported correctly oriented. But every pose I've imported for the characters Red and Sasori has had the issue with the ear. I tried the poses with two different .psks for Red (two different outfits), and both had the issue with the ear. I'm completely lost as to what could be causing this.

**Comment by cmbasnett** [comment] 2024-09-23 00:11
Are the names of the ear bones the same in the working PSKs?

Its very possible that the issue is coming from FModel itself and not the addon.

One thing to test would be to try the import into blender using the legacy addon (Beffz). If that one has the same issue then it points more towards something being wrong in FModel.

**Comment by ariannadiangelo** [comment] 2024-09-23 22:45
Yep, the names of the ear bones are the same on both PSKs. The ears also are oriented the same way when imported on both PSKs. Here is Red (breaks):
![image](https://github.com/user-attachments/assets/2e513f14-aeaf-43d0-aece-5a86d60e6a8b)
And here is Ace (does not break):
![image](https://github.com/user-attachments/assets/2b32a255-7bcd-4065-9d90-d2d383884022)
When importing with the legacy addon, Red still has the same issue with her ear, and Ace is still fine.
The problem seems to be that rotation is getting applied to the left ear at all; even though there are keyframes for the right ear, I don't think anything is actually happening during them.
Interestingly, applying Ace's intro poses to Red fixes the problem with the ear, so it seems to be something with how her specific intro poses are getting exported, maybe?

**Comment by cmbasnett** [comment] 2024-09-23 23:27
Yea, unfortunately it looks like it may be an issue with how FModel is exporting the file.

The add-on is fundamentally very simple, it will just dump the data as-is from the PSA. There's no special handling outside of the config files, so I think this is an upstream data issue. I recommend posting your issue on FModel's GitHub discussion board (though their Discord is probably a better place to get faster answers).

Going to close this as not an issue (with the add-on). Please create another issue if there's a compelling reason to believe it's the add-on that is a fault here.

**Closed by cmbasnett** 2024-09-23 23:27 UTC
Labels: supply chain issue
