### ISSUE TITLE
Importing .PSA file does nothing

### ISSUE THREAD

**Issue by yoyobatty** [DarklightGames/io_scene_psk_psa#65] opened 2024-01-16 03:45 UTC
**Versions**
Blender: 3.6.7 & 4.0.2
io_scene_psk_psa: 5.05 & 6.10

**Describe the bug**
I use the latest version of Umodel from https://www.gildor.org/en/projects/umodel#files to export my files from UT2004.
Everything successfully exports, including the mesh, animation and texture. I can import the .PSK file no problem.
I select import .PSA file, and nothing happens, it says actions imported. I see no animation in my collections. I tried both versions of blender. I even tried a different version of Umodel, same thing, the model imports no issue, the animation for either one just does nothing. It says action imported, but I don't see anything. Problem occurs in both versions of blender and both their respective compatible addons

**To Reproduce**
1. Import .PSK file, mesh visible
2. Import .PSA file, no animation visible
3. ???

**Expected behavior**
I expect the animations to import but nothing happens. 

**Screenshots**
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/32651551/0b6d8401-d73f-487d-b1d8-1250d0b10445)

**Files**

Example psk/psa files
https://1drv.ms/u/s!ArqmGMsJpcWFk3fWt6vbJuboioZL?e=R1HkA6

**Additional context**
None

**Comment by cmbasnett** [comment] 2024-01-17 00:01
This is not a bug. The actions are stored as data blocks that can be accessed and applied to your armature through one of the many animation editors (e.g., action editor, NLA etc.).

**Comment by yoyobatty** [comment] 2024-01-17 02:23
I'm not exactly sure what to do then... Blender is very new to me and I don't find it super intuitive. I check out the action editor and I see this 
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/32651551/65ff2f4c-5337-42d8-a79b-588854ada49a)

**Comment by cmbasnett** [comment] 2024-01-17 04:05
Here's a video demonstrating the use of the PSA importer and getting the actions to show up: https://github.com/DarklightGames/io_scene_psk_psa/issues/56#issuecomment-1800919076

Closing this, as there is no bug here.

**Closed by cmbasnett** 2024-01-17 04:05 UTC
Labels: invalid

**Comment by cmbasnett** [comment] 2024-01-17 04:22
Since I get this report a lot from new Blender users, I've added a [new section](https://github.com/DarklightGames/io_scene_psk_psa/blob/master/README.md#why-cant-i-see-the-animations-imported-from-my-psa.) in FAQ in the README that addresses this confusion.

**Comment by yoyobatty** [comment] 2024-01-17 11:16
I appreciate the help, I would have been completely lost without that :)
