### ISSUE TITLE
Can't export to psk

### ISSUE THREAD

**Issue by mrfrankito** [DarklightGames/io_scene_psk_psa#77] opened 2024-02-22 16:13 UTC
Hello,
I tried to export to psk my file but it says that it can't be exported.
I am using Blender v4.0.2 portable version
I attached the file here.
Thanks
[chaotic_box.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/14376378/chaotic_box.zip)

**Comment by cmbasnett** [comment] 2024-02-23 00:36
Not sure what the issue is here, I can import the PSK just fine. Can you post what the actual error you are seeing is?

**Comment by mrfrankito** [comment] 2024-02-23 00:40
The file I uploaded is .pskx, try to import it and then export to .psk
The error I get is: This is not a mesh file and it doesn't export to .psk

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/64079793/a157d9d4-afc2-43ee-826f-6608adeb2856)

**Comment by cmbasnett** [comment] 2024-02-23 01:49
You have to select the mesh object. You probably either have the armature selected. Closing this, as it is not a bug.

**Closed by cmbasnett** 2024-02-23 01:49 UTC
Labels: needs more information

**Comment by mrfrankito** [comment] 2024-02-23 03:20
I selected mesh and I get this:
"At least one bone must be marked for export"
However there are no bones in my file as you can see here, there is only one texture
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/64079793/5c2cf9ea-6437-4cf7-a63a-c0542326ff07)
