### ISSUE TITLE
Collapsing skeleton after adding action

### ISSUE THREAD

**Issue by boobzzz** [DarklightGames/io_scene_psk_psa#62] opened 2024-01-04 20:13 UTC
Hey @cmbasnett, need your help, I'm having exact the same issue as this one #59. Can you please take a look when you have a chance? Attached assets that I'm using, jumpStart animation works as expected, jumpLand is the one that causes this collapse. Added both just to compare
Add-on version: 6.1.0
Blender version: 4.0
![Screenshot 2024-01-04 221104](https://github.com/DarklightGames/io_scene_psk_psa/assets/35819774/c65b07fe-8ff8-4a99-bc69-8163f5ece379)
[assets.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/13835102/assets.zip)

**Comment by cmbasnett** [comment] 2024-01-09 02:19
@boobzzz Hey, just had a look and was able to reproduce the issue. What program was used to export these files?

**Comment by boobzzz** [comment] 2024-01-09 06:17
FModel 4.4.3.4

**Comment by cmbasnett** [comment] 2024-01-11 21:58
I think it's possible that the animations being exported are "additive" animations, meaning that the transforms in the animation are meant to be added on top of a "base" animation (this can be done in Blender using the NLA). Knowing what that base animation might be would require a more in depth knowledge of how the game plays these animations.

Does the export of the animations from FModel also come with a sidecar config file?

What game is this for, by the way?

**Comment by boobzzz** [comment] 2024-01-11 23:08
FModel exports only .psa files without a config file
This is my pet project, trying to learn UE. Being inspired by the game Returnal, decided to recreate some part of it using its assets

**Comment by boobzzz** [comment] 2024-01-14 10:41
Hey, tried to use your version of UE Viewer and have error while importing .psa. Can you please have a look?
![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/35819774/42a2b0b1-49be-4262-9799-e55606beb54e)
[SK_Player.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/13931126/SK_Player.zip)

**Comment by cmbasnett** [comment] 2024-01-14 20:57
The issue here is that UEViewer exports an invalid `.ini` format. I haven't gotten around to handling this yet as I just recently added parsing support for some well-formed config files. As a test, you can delete the `[UseTranslationBoneNames]` and everything under it's heading in the config file; it should then work.

**Comment by boobzzz** [comment] 2024-01-14 21:51
Yep, import works like a charm. But jumpLand looks collapsed as it was with FModel. Definitely this is some kind of additive animation, so I would have to figure out how to combine them together

**Comment by cmbasnett** [comment] 2024-01-17 06:30
I will open a new issue to handle the malformed config files, but I'll close this one since there's nothing actually incorrect here.

**Closed by cmbasnett** 2024-01-17 06:30 UTC
