### ISSUE TITLE
Pskx model imports with errors

### ISSUE THREAD

**Issue by 4rtb** [DarklightGames/io_scene_psk_psa#80] opened 2024-02-26 07:44 UTC
**Versions**
Blender: (3.6 and 4.0)
io_scene_psk_psa: (6.1.0 for blender 4.0 and 5.0.5 for blender 3.6)

**Describe the bug**
Pskx model imports with errors

**To Reproduce**
1. Import included to issue pskx model
2. Import it into scene
3. See error

**Expected behavior**
The import went fine without errors

**Screenshots**
![Безымянный](https://github.com/DarklightGames/io_scene_psk_psa/assets/141040913/4a39fc84-efce-4357-b2d0-b84b9226e079)

**Files**
https://www.mediafire.com/file/kh9j1egbcz2jdm3/Hazmat_RIG.pskx/file

**Additional context**
[26.02.2024 10_44.webm](https://github.com/DarklightGames/io_scene_psk_psa/assets/141040913/ea37ed33-ebcf-4d28-915a-e84e93419ad4)

**Comment by colinbasnettskyboxlabs** [comment] 2024-02-27 23:47
To be fair, this is a warning and not an error.

The faces are being discarded because they are either duplicates of existing faces or are degenerate faces (faces where two or more of the vertices are identical). This is usually due to an issue caused by the program that created the PSK. This could be "fixed" on my end by creating a second object to put all the problematic faces on, but in my experience this is not needed nor desirable.

**Comment by cmbasnett** [comment] 2024-02-27 23:48
To be fair, this is a warning and not an error.

The faces are being discarded because they are either duplicates of existing faces or are degenerate faces (faces where two or more of the vertices are identical). This is usually due to an issue caused by the program that created the PSK. This could be "fixed" on my end by creating a second object to put all the problematic faces on, but in my experience this is not needed nor desirable.

**Comment by cmbasnett** [comment] 2024-02-29 08:35
Closing this as there's nothing actually wrong here. If there's actually an error on the model you notice that's related to this, please re-open a new issue.

**Closed by cmbasnett** 2024-02-29 08:35 UTC
