### ISSUE TITLE
Error when exporting PSK

### ISSUE THREAD

**Issue by heloess** [DarklightGames/io_scene_psk_psa#60] opened 2023-12-01 11:02 UTC
Blender: (example: 4.0)
io_scene_psk_psa: (example: 6.0.0)

![image](https://github.com/DarklightGames/io_scene_psk_psa/assets/96503452/aa30de80-ae47-44d2-9a0b-7b818dbd5423)

**Comment by cmbasnett** [comment] 2023-12-04 22:23
Can you send the PSK so I can try this out locally?

**Comment by cmbasnett** [comment] 2023-12-05 23:38
@heloess Can you send the PSK so I can try this out locally?

**Comment by cmbasnett** [comment] 2023-12-14 21:15
@heloess Actually, I know what the issue is here. The non-extended PSK format  has a limit of 65536 "wedges" (UV corners).  The PSK exporter here is erroring out here because it does not export the "extended" format that has in increased wedge limit. I made the assumption that there wouldn't be much point in exporting a PSK that would be incompatible with any of the game engine importers.

I can update the exporter to handle exporting the extended format, but I'd want to gate this behind an option that the user must enable so that people don't accidentally export incompatible PSKs.

If I may ask, what program is going to ingest this exported PSK?

**Comment by cmbasnett** [comment] 2024-01-22 21:56
@heloess Can you please send the file you used to trigger this error? Otherwise I will be forced to close the issue.

**Comment by cmbasnett** [comment] 2024-02-02 20:41
Closing this since the OP hasn't responded.

**Closed by cmbasnett** 2024-02-02 20:41 UTC
Labels: needs more information
