### ISSUE TITLE
IndexError when exporting

### ISSUE THREAD

**Issue by EmeraldOx** [DarklightGames/io_scene_psk_psa#23] opened 2022-08-02 20:54 UTC
Hi, so sorry if I am posting this incorrectly, I've never commented on Github before. When attempting to export as a PSK I was given this error:
![psk error](https://user-images.githubusercontent.com/6391195/182468403-082c35ec-8da8-4d11-a8dc-a2c857a3cfe1.png)
I am using Blender 2.93. I am new to Blender as well so this could be a problem on my end that I can fix myself. Any help would be appreciated.

**Comment by cmbasnett** [comment] 2022-08-06 05:06
Could you send the .blend file that you are attempting to export? This is definitely a bug, but without the .blend file I cannot reproduce the error.

**Comment by cmbasnett** [comment] 2022-08-31 05:40
@EmeraldOx would you be able to provide the .blend file that can reproduce this error? If not, I'll have to close this issue.

**Closed** 2022-09-03 22:03 UTC
Labels: bug, needs more information
