### ISSUE TITLE
Error when exporting PSA

### ISSUE THREAD

**Issue by midgetbanana** [DarklightGames/io_scene_psk_psa#76] opened 2024-02-16 18:18 UTC
i have the armature that has the animation selected, on the export window i have the action checked, however when i export PSA I'm getting "AttributeError: 'NoneType' object has no attribute 'animation_data'"

i exported as fbx and imported it on a fresh blend file to try exporting again and this time i got "AttributeError: 'Object' object has no attribute 'bones'"

i'm new to this so i'm very likely doing something wrong but i've no idea what else to do

![Untitled](https://github.com/DarklightGames/io_scene_psk_psa/assets/62650565/da4d1b68-1bc1-4880-85ad-89f64448107d)

**Comment by cmbasnett** [comment] 2024-02-16 20:45
Please send the .blend file you're using, otherwise I cannot reproduce this.

**Comment by midgetbanana** [comment] 2024-02-17 08:09
[baikonur2.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/14318153/baikonur2.zip)

hope it helps

**Comment by midgetbanana** [comment] 2024-02-17 08:10
[baikonur2.zip](https://github.com/DarklightGames/io_scene_psk_psa/files/14318164/baikonur2.zip)

hope it helps

**Comment by cmbasnett** [comment] 2024-02-18 07:03
Thanks, I found the issue. There was a hidden setting that you must have been turned on by accident that caused the error due to some faulty programming. It will be fixed in a coming patch!

**Comment by cmbasnett** [comment] 2024-02-29 08:42
This has been fixed in [6.2.0](https://github.com/DarklightGames/io_scene_psk_psa/releases/tag/6.2.0).

**Closed by cmbasnett** 2024-02-29 08:42 UTC
Labels: bug, fixed in next release
